services:
  imageassurance:
    build: ./app
    image: imageassurance
    container_name: containerassurance
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GROQ_API_KEY: ${GROQ_API_KEY}
      API_URL: ${API_URL}
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health')\" || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 900s

  ui:
    build: ./ui
    image: uiassurance
    container_name: uiassurance
    ports:
      - "8501:8501"
    depends_on:
      imageassurance:
        condition: service_healthy
    environment:
      API_URL: ${API_URL}
      

  db:
    image: postgres:15
    container_name: assurance_db
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: assurance_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d assurance_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
